hash-format = "sha256"

[[files]]
file = "config/defaultoptions/iris.propertie.default"
hash = "d16d31af49c45af4e8b371efa066e0a16a262e6afb575415b16450a7e96fa2c5"

[[files]]
file = "config/defaultoptions/iris.properties"
hash = "d16d31af49c45af4e8b371efa066e0a16a262e6afb575415b16450a7e96fa2c5"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "de419d7382cb180a110413d288b8e2b17a9f5915c66a4f6b086956f0665403a0"

[[files]]
file = "config/defaultoptions/keybindings.txt.default"
hash = "de419d7382cb180a110413d288b8e2b17a9f5915c66a4f6b086956f0665403a0"

[[files]]
file = "config/defaultoptions/options.txt"
hash = "7e2714222d145b60b9910dadd2c6a2531ed223857bb3f3de1898ebeb9982a1bb"

[[files]]
file = "config/defaultoptions/options.txt.default"
hash = "0f138f84d6823f343baea9677a8b70ae9bd7a8f61db41b8c46b56330eab1d1a1"

[[files]]
file = "config/defaultoptions/servers.dat"
hash = "3f243f23601d561db4807d6f8476cc238fac33fe3186f1eff69310158777f8c9"

[[files]]
file = "config/defaultoptions/servers.dat.default"
hash = "3f243f23601d561db4807d6f8476cc238fac33fe3186f1eff69310158777f8c9"

[[files]]
file = "config/fancymenu/assets/romangho_2.png"
hash = "fb892e55cba963759979857d451baa8e2b1642248fa7360a4c67d98cb5088ccb"

[[files]]
file = "config/fancymenu/assets/romangho_bg.png"
hash = "7d516c199c92950e0a0c78980dd71bf416297a326ddc7bfe04762b6a567e2368"

[[files]]
file = "config/fancymenu/custom_gui_screens.txt"
hash = "ff492043eaf454c46e949d5eef32ece90cc5a19feb50a161dd29a43b5732c880"

[[files]]
file = "config/fancymenu/customizablemenus.txt"
hash = "9f0ada5a7f0193d2d717d1c1736f545f5235c2597213731493b97488617ebbf2"

[[files]]
file = "config/fancymenu/customization/romangho_layout.txt"
hash = "7ea64961aa50d078bfdbdf10da2f508b5db701b64ec56e2c543a88df9b310823"

[[files]]
file = "config/fancymenu/images/romangho_bg.png"
hash = "7d516c199c92950e0a0c78980dd71bf416297a326ddc7bfe04762b6a567e2368"

[[files]]
file = "config/fancymenu/layout_editor/widgets/element_layer_control.lewidget"
hash = "d4e66bc22fcfa56158ca7100017623c71b1437fb4722229b6e064e0a48a5f5de"

[[files]]
file = "config/fancymenu/legacy_checklist.txt"
hash = "9a25d3dc708e43eabafce5479a13c02dae15bc7f673afb2745b8b2ba48a97dc0"

[[files]]
file = "config/fancymenu/options.txt"
hash = "4553589dd1eaf0fa55d893fd2a0226b5cb8464147f8e65bb2c93700fa1081a4c"

[[files]]
file = "config/fancymenu/ui_themes/dark.json"
hash = "3f1263eaf693fdb6a315099b06797ac18830faa66c620916a80337a5082fd850"

[[files]]
file = "config/fancymenu/ui_themes/light.json"
hash = "3fcfc5f9957fbb86aea846c9ad49a24f47ca709c523c4018b584668e38b72f41"

[[files]]
file = "config/fancymenu/user_variables.db"
hash = "3d7d4cda73d6bde134a568ccbe4e8d2e7fbe701570012b71fa45acdb2258c823"

[[files]]
file = "config/iris.properties"
hash = "346d31902bb27ca558038f5f72558add5f87788941c9e1191c46cb37bb042194"

[[files]]
file = "mods/CustomNPCs-Unofficial-NeoForge-1.21.1.20250917.jar"
hash = "91f8d7d2e873739be576bf89a54aa2d999a38455d3660405338767e311e3a0c4"

[[files]]
file = "mods/Jade-1.21.1-NeoForge-15.10.3.jar"
hash = "7087a9672a208071e774571423793d499a56adc8dd09fabe36f8652a3bb9c418"

[[files]]
file = "mods/MoreMobGriefingOptions-1.21.1-3.0.0.jar"
hash = "1e79e349f40a62ae02d0bc9872aefaf0f614be7b4a4c954005e2da628566c28a"

[[files]]
file = "mods/MouseTweaks-neoforge-mc1.21-2.26.1.jar"
hash = "68e6f4201c5de97b77929a7215c9552495696ca6a3bf3ae4eacc34e135f6cc8b"

[[files]]
file = "mods/Neat-1.21-40-NEOFORGE.jar"
hash = "06f4334e23b3561c10c0425531a56df3aefbb193c26140fbd9c85ea08c5c48d5"

[[files]]
file = "mods/TerraBlender-neoforge-1.21.1-4.1.0.8.jar"
hash = "edb34c388fe17ea88d0a7fd11174bbf8ae8f28a4c8ce886f1bf9a5cf0ebc36b8"

[[files]]
file = "mods/TreeChop-1.21.1-neoforge-0.19.3.jar"
hash = "2a5ec9cca187b4a031e9dd7e5eec8d0872f7d2bc355d88bda633021fa7eb71b0"

[[files]]
file = "mods/YungsApi-1.21.1-NeoForge-5.1.6.jar"
hash = "08e1d21690d3213a4c62de6b6cf79f3527afb2e72e0cad0e1848d46eb8f682ca"

[[files]]
file = "mods/YungsBetterCaves-1.21.1-NeoForge-3.1.4.jar"
hash = "aa94ae3e7fdacb469459bf45be60c35bebfebe0488a79e31c7686d746939701d"

[[files]]
file = "mods/YungsBetterDesertTemples-1.21.1-NeoForge-4.1.5.jar"
hash = "2c3191ad447092cc7873a06e92f16bd3e2ff9dc31e93268b8893d06dd89e1fd6"

[[files]]
file = "mods/YungsBetterDungeons-1.21.1-NeoForge-5.1.4.jar"
hash = "61816c3b7c9d92c6b44f93dce87ceb0a22827f20285d5d9c4d10d519d734de04"

[[files]]
file = "mods/YungsBetterEndIsland-1.21.1-NeoForge-3.1.2.jar"
hash = "8005f1ea798d09fc05dad07a21ed1f393a523a718197cdbd37b1ce6d9a17e4a4"

[[files]]
file = "mods/YungsBetterJungleTemples-1.21.1-NeoForge-3.1.2.jar"
hash = "a0d57b78c7a1891796f342b1f09c214bc27bedf0a3a894f029dfdb2db9f813d0"

[[files]]
file = "mods/YungsBetterMineshafts-1.21.1-NeoForge-5.1.1.jar"
hash = "5625930dfb3240820d6e4ecf55fff0c39f70ce782fad117a4d418251184c7be0"

[[files]]
file = "mods/YungsBetterOceanMonuments-1.21.1-NeoForge-4.1.2.jar"
hash = "cdcf8fe0e08c75261048d43c6ed4898972d23e096dd04a2524c136f06416ab02"

[[files]]
file = "mods/YungsBetterStrongholds-1.21.1-NeoForge-5.1.3.jar"
hash = "a9cab2fc01538368862365691f7d215309801aed0b390351681b6b60a1db7b58"

[[files]]
file = "mods/YungsBetterWitchHuts-1.21.1-NeoForge-4.1.1.jar"
hash = "888b1e6d1ada21982a75abfb4afb040c9bc2cc68777ec5fcd1199b978e3d4f8d"

[[files]]
file = "mods/YungsBridges-1.21.1-NeoForge-5.1.1.jar"
hash = "bf93a85422a6b457358c3b56352641a97ec09cc37dec18b2cedcac2bd1ff9bec"

[[files]]
file = "mods/YungsCaveBiomes-1.21.1-NeoForge-3.1.1.jar"
hash = "7585587e5cb7859e26189c6ec0a5b829c5c228f095e4e843fa3add61f817dd20"

[[files]]
file = "mods/YungsExtras-1.21.1-NeoForge-5.1.1.jar"
hash = "0cd26474e514f5dc3114aaf5ec7e049bcd285f0c5db191bb45223193f35df70d"

[[files]]
file = "mods/accessories-neoforge-1.1.0-beta.52+1.21.1.jar"
hash = "7a3f655c1593b14424b678b5f06c6f87374b8551aa7496dae5e64143ae5a59b0"

[[files]]
file = "mods/appleskin-neoforge-mc1.21-3.0.7.jar"
hash = "99a2f1b22f05b1215c6c967c0cf0518a39d30e18a94ac3dac248385e38dcfe10"

[[files]]
file = "mods/architectury-13.0.8-neoforge.jar"
hash = "5ec578f814e8cca87aeffa6e424032e78d9ea5ea6b603dd834c2dc13c31141ee"

[[files]]
file = "mods/artifacts-neoforge-13.1.0.jar"
hash = "b666075d627021c98f7c07fb55676d35ea594700e157a295179384c2a9ecb622"

[[files]]
file = "mods/attributefix-neoforge-1.21.1-21.1.3.jar"
hash = "b2b20f3d44e824071284c14de3f4d3323d420e1c450040b339a5c37d2c382ad4"

[[files]]
file = "mods/balm-neoforge-1.21.1-21.0.55.jar"
hash = "eba756d2e0a5e1a06e0c2ec0c45db06f4e15da37f9e63c08f66f8ecb4cf2dd7d"

[[files]]
file = "mods/bookshelf-neoforge-1.21.1-21.1.80.jar"
hash = "59a49a5bd7c6e294b00eed4d6e085d3b8fa0cc30278aff8d9634845becf0d8ac"

[[files]]
file = "mods/caramelChat-mc1.21.1-neoforge-1.2.2.jar"
hash = "07418cca73aa3020edd1f3da548648afc532fe2b01822a0405eb3672c16639a6"

[[files]]
file = "mods/carryon-neoforge-1.21.1-2.2.2.11.jar"
hash = "b18c734fb574c05c78dd33c4cd4c152e55efc8aecc0b6de876cc21be3c147f7f"

[[files]]
file = "mods/cloth-config-15.0.140-neoforge.jar"
hash = "65e722e0d98431a07c45f8bdd8d529a217cc8c175fde1740248bd5c1b4f3c0d4"

[[files]]
file = "mods/combat_roll-neoforge-2.0.6+1.21.1.jar"
hash = "4904ae4c392d51c431c915822d817de608fd524632021ce417a17ce1a0185f17"

[[files]]
file = "mods/cosmeticarmorreworked-1.21.1-v1-neoforge.jar"
hash = "6328049755735159c55f5918ac301cff53a8d8790c3fe63e32e7d8a0e37f123f"

[[files]]
file = "mods/cristellib-neoforge-1.21.1-3.0.2.1.jar"
hash = "bb3ac15b080320e4da25ffb44c5a7a528ddd7bf7a16e567831048bd13e0528bb"

[[files]]
file = "mods/curios-neoforge-9.5.1+1.21.1.jar"
hash = "a45df2125c26219974aba7507ffc9afe7b83acc941a386af3faacb1cc0056fde"

[[files]]
file = "mods/default_skill_trees-1.1.jar"
hash = "6038a4843f19ad09972cf8b218ea311ed86188c9575c866c7903202660de5d4f"

[[files]]
file = "mods/defaultoptions-neoforge-1.21.1-21.1.5.jar"
hash = "a42f0ff542725b5a56b82f5e8ad064ba778392e3f81e2b8b2c0a48f3712c2fc3"

[[files]]
file = "mods/enchdesc-neoforge-1.21.1-21.1.9.jar"
hash = "74d546ecb147da7e2cb53fe3115f6e062094329dcf15639b3da694cc00d3f843"

[[files]]
file = "mods/fancymenu_neoforge_3.8.1_MC_1.21.1.jar"
hash = "d935c9862541a41083f0ab086684b0510a924c05f609f8935f7fab6fbe843613"

[[files]]
file = "mods/ferritecore-7.0.2-neoforge.jar"
hash = "235e2081dfe050d7642b0d432a786668f079168505ba5d6bf0ec70c962a36539"

[[files]]
file = "mods/forgified-fabric-api-0.116.7+2.2.0+1.21.1.jar"
hash = "d2ab54c332781b1d7bbaec8f071281989e186d8022cf397c3e25d2ae532be0b2"

[[files]]
file = "mods/framework-neoforge-1.21.1-0.13.6.jar"
hash = "1fe747d28614d72797e8478f109d3bafac4e07b845da57228adb1a6305ba0fd1"

[[files]]
file = "mods/geckolib-neoforge-1.21.1-4.8.2.jar"
hash = "a733757157bd914b56a24c09d2797c522f0f339eb5e45ec1d70a8a9326ecd9df"

[[files]]
file = "mods/immersive_armors-1.7.5+1.21.1-neoforge.jar"
hash = "69a2a6482d446529e2c402ab94da7abd4a1ab63acb08578575ebdd166fe76b13"

[[files]]
file = "mods/inventoryhud.neoforged.1.21.1-3.4.28.jar"
hash = "1bbd368273b299857ccdb236d096169d289513f67e7561d4743375b55f5a584a"

[[files]]
file = "mods/iris-neoforge-1.8.12+mc1.21.1.jar"
hash = "3e3f94d2d5cdcb8145c4385d521974aa2d8669b2cc212351f70cf06488182e83"

[[files]]
file = "mods/journeymap-neoforge-1.21.1-6.0.0-beta.53.jar"
hash = "f1d6b029e969104743a5a37b7ef4b5fe3321780c110d92ce6b11d144c74775cd"

[[files]]
file = "mods/konkrete_neoforge_1.9.9_MC_1.21.jar"
hash = "791c5538751dd3015ef3a2ce92d98719e1a28a48ebbd817b78506771256654cd"

[[files]]
file = "mods/lootr-neoforge-1.21.1-1.11.36.105.jar"
hash = "5210dd35d6314b97383e5da900d98fa634f2b977e55572239043d575a67ff69b"

[[files]]
file = "mods/mcw-bridges-3.1.1-mc1.21.1neoforge.jar"
hash = "9a140c6a1014f1f80b887fc629a4e1ef9ff3036b07a27803dcf44d32dd543b91"

[[files]]
file = "mods/mcw-furniture-3.4.1-mc1.21.1neoforge.jar"
hash = "819fda8059b210e9de8b9275c8b8e0d931054af5a5ad47771c72d9fd4ab85e88"

[[files]]
file = "mods/mcw-mcwfences-1.2.1-mc1.21.1neoforge.jar"
hash = "e4b0e5a5b67decc2285e71f017fb4f60284796fa0838de3edeaf6b7cb0395735"

[[files]]
file = "mods/mcw-mcwpaths-1.1.1-mc1.21.1neoforge.jar"
hash = "f04b51518f75c8a7d5fe1be5589dbcb8a7b0d4f67373ca903578804d971b1286"

[[files]]
file = "mods/mcw-mcwstairs-1.0.2-mc1.21.1neoforge.jar"
hash = "177fe382ff22caa14983d862ead2717321315a5e4afa778d245e9acd2f61608d"

[[files]]
file = "mods/mcw-mcwwindows-2.4.2-mc1.21.1neoforge.jar"
hash = "8970c40ec622edd34c9b055226b403af08ab441c77303a6dc625ae18005f8184"

[[files]]
file = "mods/mcw-roofs-2.3.2-mc1.21.1neoforge.jar"
hash = "25c79def993a24b05b0f8494ee9417717d469bc000d5ed7c219b47dcc3b3e9c8"

[[files]]
file = "mods/melody_neoforge_1.0.10_MC_1.21.jar"
hash = "6b973a4564703c531fc0eae09db08b07a38091e0a743c687b8d2049457e84871"

[[files]]
file = "mods/modernfix-neoforge-5.25.1+mc1.21.1.jar"
hash = "2dbcf6cd837fca938323dd55114e6c515a4bb1b644a746aad504dd8d43bb0b6d"

[[files]]
file = "mods/modnametooltip-1.21.1-neoforge-2.3.0.jar"
hash = "41ae4040808e06f796d53dd4f68df266c1a6f5230b915fd16e359965c826467f"

[[files]]
file = "mods/overloadedarmorbar-neoforge-1.21-2.jar"
hash = "d9c809d62e4dac5e2dabfd6c672bbe47e89e41f680d0937aa59e49f7f65ff405"

[[files]]
file = "mods/owo-lib-neoforge-0.12.15.5-beta.1+1.21.jar"
hash = "de6ed336bd80154b7241a7b3276694befc1c94550add8bcdfe7f82e5172fd13d"

[[files]]
file = "mods/picaxe-1.21.1-neoforge-1.0.9.jar"
hash = "57cc24f8c899198fc24bf103786a4058a35aefe59e69230c50008ff1c32dea77"

[[files]]
file = "mods/player-animation-lib-forge-2.0.1+1.21.1.jar"
hash = "15ef231ca57ad2a237a3760dd9aa17b34926fc6e8bf07564434969534c70aa3e"

[[files]]
file = "mods/prickle-neoforge-1.21.1-21.1.11.jar"
hash = "ccf46c442ed3c7fe41ad056f0940560829ec4dd88360985dfacd78f4614eb167"

[[files]]
file = "mods/puffish_skills-0.17.1-1.21-neoforge.jar"
hash = "dfcb568d576b2ba4cdc339bd8d6ba70c7b842772496b5affb333de374abe2737"

[[files]]
file = "mods/ranged_weapon_api-neoforge-2.3.3+1.21.1.jar"
hash = "49f439f6b771aeecebeeacc1e920761ba75a8da6ce71026e18412af06ec66405"

[[files]]
file = "mods/refurbished_furniture-neoforge-1.21.1-1.0.20.jar"
hash = "d2fad0e9f710de93c247cdc79e6eb486ccb4b6cdc55e29a2373f54cb6900f0ac"

[[files]]
file = "mods/repurposed_structures-7.5.17+1.21.1-neoforge.jar"
hash = "8299ac9bedb488d65bae351d529caad6a9072dc59f46bc50d599525efa882a34"

[[files]]
file = "mods/sodium-neoforge-0.6.13+mc1.21.1.jar"
hash = "7acd7af2ef75ec883a6872c17494ead65e38025151eb08a1d60e36d34377f403"

[[files]]
file = "mods/sophisticatedbackpacks-1.21.1-3.25.20.1470.jar"
hash = "636bcbeb0f834de005ea363124cfff3849e09db39eabd2d2b3f2f971c5caeeaf"

[[files]]
file = "mods/sophisticatedcore-1.21.1-1.3.98.1332.jar"
hash = "649fe16fdc0dec6c7634419aab07a692ee1ede8c1d01a033c806890673b23d29"

[[files]]
file = "mods/sophisticatedstorage-1.21.1-1.5.18.1405.jar"
hash = "4eb3a36f7bca9030434e242aec603444921f37c65e329271098eeab1a83ec869"

[[files]]
file = "mods/spell_engine-neoforge-1.8.16+1.21.1.jar"
hash = "57b6a44b111d7a085fdfc3d05dd1f9a1b1d50128416ad7498ff998d479860188"

[[files]]
file = "mods/spell_power-neoforge-1.4.6+1.21.1.jar"
hash = "b5457fd85e36e839b5d18c215ac1d113ae5d3e1a8dbc48a342d906a93da9a380"

[[files]]
file = "mods/t_and_t-neoforge-fabric-1.13.7+1.21.1.jar"
hash = "925d61a8cee8ca013bac15cda2fcfbdf647eb1cde50c414c18298ea3a627c640"

[[files]]
file = "mods/torchmaster-neoforge-1.21.1-21.1.9.jar"
hash = "db9a2fa385757656797a5a14ffad1777fbe596e2e443f1deba5f7534706eb806"

[[files]]
file = "mods/waystones-neoforge-1.21.1-21.1.25.jar"
hash = "53cf4c5ca2ee9b30246008e9d8ca4fb084a4527ce9fc26ec4d916a9cba6dba07"

[[files]]
file = "mods/worldedit-mod-7.3.8.jar"
hash = "5e7752c97876d87411e3760bcc573cc431f43c453722e6959fa7fe54db1b01ca"

[[files]]
file = "servers.dat"
hash = "23a7838bce8eff9c42e1ae6dddb43ee40e98920b5972ee4c303ebef91e5ee1b1"

[[files]]
file = "servers.dat.default"
hash = "23a7838bce8eff9c42e1ae6dddb43ee40e98920b5972ee4c303ebef91e5ee1b1"

[[files]]
file = "shaderpacks/BSL_v10.1p1.zip"
hash = "aca54360ec808b5c11e9a5bdaa5516ad9eaee494225c0199580103650bf74f59"
