name = "Romangho"
author = "Rw"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecfe880e81d50597457216c4a476cdaaddec8db25fe93f1555c45e1ab2ca408c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
