name = "Romangho"
author = "Rw"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc7c5e099de5af9a3f7fab71bdd312eac891d013a6843e1bb254f33336c16da4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
