name = "Romangho"
author = "Rw"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f63bdabe4e829112e89587ea098a8bbba5537b531b84e527b1f5044ba86d74d1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
