name = "Romangho"
author = "Rw"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a778bef6d5c35a22dc15a46f26ec954711df0babe9521f033d0b2ef309afbc06"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
