name = "Romangho"
author = "Rw"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44aa7edcee9acd687dbd2e0984befe70b0998f6f4d03c8bba70ede7647bec930"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
