name = "Romangho"
author = "Rw"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3e8c2eefff8ef19345c809b45973eb4ea51eb1fc57e91fc582414e28e1621cf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
