name = "Romangho"
author = "Rw"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2831d87ff4e5e749e14172fc016df7d75381f270a6bb49657cf985552e8f9768"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
