name = "Romangho"
author = "Rw"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf7ec23cc20b18c63bf829422a75cc8ebfeee8f90646f869122427c6454d7938"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
