name = "Romangho"
author = "Rw"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f10283509a76873538853735a923e41bcf737a3fc6c552e567ef1f9714ba6e09"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
