name = "Romangho"
author = "Rw"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d3d0cff82e05fb3abe5d0aff415fac6bc604f346d387768bc356e35236b9847"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
